# Generated by Django 4.2.4 on 2026-08-15 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="profile_photos/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_photo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("LOGIN", "Login"),
                            ("TOKEN_GENERATION", "Token Generation"),
                            ("TOKEN_REGENERATION", "Token Regeneration"),
                        ],
                        max_length=32,
                    ),
                ),
                ("image", models.ImageField(upload_to="security_photos/%Y/%m/%d/")),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSING", "Processing"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "face_recognition_status",
                    models.CharField(
                        choices=[
                            ("NOT_RUN", "Not Run"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="NOT_RUN",
                        max_length=32,
                    ),
                ),
                ("face_confidence", models.FloatField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_security_photo_user"),
                    models.Index(
                        fields=["event_type"], name="idx_security_photo_event"
                    ),
                    models.Index(
                        fields=["captured_at"], name="idx_security_photo_captured"
                    ),
                    models.Index(
                        fields=["verification_status"], name="idx_photo_verif_status"
                    ),
                ],
            },
        ),
    ]
